# Generated by Django 5.1.1 on 2024-12-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimagemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loanmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
